---
name: Build demoapp-backend

# Events: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  push:
    branches:
      - main
      - release/.*
    paths-ignore:
      - '**.md'
  workflow_dispatch:
jobs:
  lint:
    uses: ./.github/workflows/lint.yml    # Workflow calls need to be executed as jobs
    with:
      yaml: true
