---
name: Build demoapp-backend

# Events: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  # Run workflow on push except for ignored branches and paths
  push:
    # Secrets aren't available for dependabot on push. https://docs.github.com/en/enterprise-cloud@latest/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/troubleshooting-the-codeql-workflow#error-403-resource-not-accessible-by-integration-when-using-dependabot
    branches-ignore:
      # - 'dependabot/**'
      - 'cherry-pick-*'
    paths-ignore:
      - '**.md'    # Ignore documentation changes
      - '.github/dependabot.yml'    # Ignore dependabot changes
  # Allow user to manually trigger Workflow execution
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4    # https://github.com/marketplace/actions/checkout
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3    # https://github.com/marketplace/actions/docker-setup-qemu
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3    # https://github.com/marketplace/actions/docker-setup-buildx
      # - name: Build container image
      #   uses: docker/build-push-action@v5    # https://github.com/marketplace/actions/build-and-push-docker-images
      #   with:
      #     context: .
      #     file: Containerfile
      #     push: false
      #     tags: demoapp-backend
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max
