---
# Build Application and Upload Container Image to Docker Hub
name: Build

# Events: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  # Run workflow on push except for ignored branches and paths
  push:
    # Secrets aren't available for dependabot on push. https://docs.github.com/en/enterprise-cloud@latest/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/troubleshooting-the-codeql-workflow#error-403-resource-not-accessible-by-integration-when-using-dependabot
    branches-ignore:
      # - 'dependabot/**'
      - 'cherry-pick-*'
    paths-ignore:
      - '**.md'    # Ignore documentation changes
      - '.github/dependabot.yml'    # Ignore dependabot changes
  # Allow user to manually trigger Workflow execution
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4    # https://github.com/marketplace/actions/checkout

      # Setup Java and cache Maven dependencies
      - uses: actions/setup-java@v3    # https://github.com/actions/setup-java
        with:
          distribution: microsoft    # Microsoft was selected to match Visual Studio Code Dev Container Java distribuition, see .devcontainer/devcontainer.json. Supported distributions: https://github.com/actions/setup-java#supported-distributions
          java-version: '17'    # Java version must match `project.properties['java.version']` in pom.xml
          cache: maven

      # Build with Maven and Upload Container Image to Docker Hub
      # Docker Hub repositor: https://hub.docker.com/repository/docker/paulgilber/demoapp-backend
      - name: Build
        env:
          DOCKER_REGISTRY_URL: docker.io/paulgilber/
          DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
        run: |
          mvn clean package \
            -Ddocker.registry.url= ${{ env.DOCKER_REGISTRY_URL }} \
            -Ddocker.registry.username= ${{ env.DOCKER_REGISTRY_USERNAME }} \
            -Ddocker.registry.password= ${{ env.DOCKER_REGISTRY_PASSWORD }}

      # Uncomment lines below to build with Docker
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3    # https://github.com/marketplace/actions/docker-setup-qemu
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3    # https://github.com/marketplace/actions/docker-setup-buildx
      # - name: Build container image
      #   uses: docker/build-push-action@v5    # https://github.com/marketplace/actions/build-and-push-docker-images
      #   with:
      #     context: .
      #     file: Containerfile
      #     push: true
      #     tags: paulgilber/demoapp-backend
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max
