---
# Workflow syntax for GitHub Actions: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
# SonarCloud: https://sonarcloud.io/
name: Scan Code with SonarCloud

# Events: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  # Run workflow on push except for ignored branches and paths
  push:
    paths-ignore:
      - '**.md'    # Ignore documentation changes
      - '.github/workflows/build.yml'    # Ignore workflow changes
      - '.github/workflows/code-scan-codecov.yml'    # Ignore workflow changes
      - '.github/workflows/code-scan-codeql.yml'    # Ignore workflow changes
      - '.github/workflows/merge-cleanup.yml'    # Ignore workflow changes
  # Run workflow on pull request
  pull_request:    # By default, a workflow only runs when a pull_request event's activity type is opened, synchronize, or reopened

# Run a single job at a time: https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: sonarcloud-${{ github.ref }}
  cancel-in-progress: true

# Set Workflow-level permissions: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions:
  contents: read

jobs:
  codeql:
    runs-on: ubuntu-latest    # GitHub-hosted runners: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    environment: sonarcloud    # Use `sonarcloud` repository environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4    # https://github.com/marketplace/actions/checkout
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2.0.2    # https://github.com/marketplace/actions/sonarcloud-scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    # GITHUB_TOKEN is a special secret automatically generated by GitHub: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # SONAR_TOKEN must be defined in `sonarcloud` repository environment

      # In case you need to override default settings
      # - name: Analyze with SonarCloud
      #   uses: sonarsource/sonarcloud-github-action@v2.0.2
      #   with:
      #     projectBaseDir: my-custom-directory
      #     args: >
      #       -Dsonar.organization=my-organization
      #       -Dsonar.projectKey=my-projectkey
      #       -Dsonar.python.coverage.reportPaths=coverage.xml
      #       -Dsonar.sources=lib/
      #       -Dsonar.test.exclusions=tests/**
      #       -Dsonar.tests=tests/
      #       -Dsonar.verbose=true
