---
# Workflow syntax for GitHub Actions: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: Lint Files

# Events: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  # Run workflow on push except for ignored branches and paths
  push:
    branches-ignore:
      - 'cherry-pick-*'
    paths:
      - '**.yaml'
      - '**.yml'
      - '**.yamllint'
  # Run workflow on pull request
  pull_request:    # By default, a workflow only runs when a pull_request event's activity type is opened, synchronize, or reopened

  # Allow other Workflows to call this Workflow
  workflow_call:

# Run a single job at a time: https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cancel-on-merge:
    runs-on: ubuntu-latest
    permissions:
      actions: write    # Allow this job to cancel a workflow run
    steps:
      - name: Cancel when triggered by Merge commit
        # `push` event payload: https://docs.github.com/en/webhooks/webhook-events-and-payloads#push
        if: github.event_name == 'push' && contains(toJSON(github.event.head_commit.message), 'Merge pull request ')
        # Cancel a workflow run: https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#cancel-a-workflow-run
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/cancel
  lint:
    runs-on: ubuntu-latest    # GitHub-hosted runners: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4    # https://github.com/marketplace/actions/checkout
      - name: YAML Lint
        run: yamllint .   # yamllint is pre-installed: https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#tools
